add Sandbox endpoint for testIPN
ammario/paypal-ipn pull request #1
Opened 2018-04-28 06:08 UTC by zsying

2018-04-29 01:24 UTC, ammario requested changes
Thank you for the contribution!

Please fix these typos and we can merge.

2018-04-29 01:24 UTC, ammario commented on listener.go
> +//SandboxIPNEndpoint the Sandbox notification verification URL
`SandboxIPNEndpoint is`

2018-04-29 01:24 UTC, ammario commented on listener.go
> +func getEndpint(testIPN bool) string {
`endpoint`

2018-05-02 09:58 UTC, zsying commented on listener.go
> +//SandboxIPNEndpoint the Sandbox notification verification URL
done

2018-05-02 09:58 UTC, zsying commented on listener.go
> +func getEndpint(testIPN bool) string {
done

2018-05-02 16:28 UTC, ammario approved these changes

2018-05-02 16:28 UTC, merged